export const dummyDevices = [
  {
    serialNo: "JTD-512312",
    theatreName: "Kriplle Square",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    bandwidth: "1 Gbps",
    avgBandwidth: "812 Kbps",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
  },
  {
    serialNo: "JTD-912312",
    theatreName: "Cross River Mall",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    bandwidth: "512 Kbps",
    avgBandwidth: "512 Kbps",
    deviceStatus: "Online",
    downloadStatus: "Cancelled",
    osVersion: "5.2.1.3",
  },
  {
    serialNo: "JTD-523124",
    theatreName: "Fairy Street",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    bandwidth: "1 Gbps",
    avgBandwidth: "919 Kbps",
    deviceStatus: "Online",
    downloadStatus: "Downloading",
    osVersion: "5.2.1.2",
  },
  {
    serialNo: "JTD-942223",
    theatreName: "Kelly's",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    bandwidth: "1 Gbps",
    avgBandwidth: "812 Kbps",
    deviceStatus: "Online",
    downloadStatus: "Downloading",
    osVersion: "5.1.21",
  },
  {
    serialNo: "JTD-412431",
    theatreName: "Oplain Center",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    bandwidth: "256 Kbps",
    avgBandwidth: "124 Kbps",
    deviceStatus: "Online",
    downloadStatus: "Downloading",
    osVersion: "5.2.1.3",
  },
  {
    serialNo: "JTD-361623",
    theatreName: "Para Mall",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    bandwidth: "1 Gbps",
    avgBandwidth: "919 Kbps",
    deviceStatus: "Online",
    downloadStatus: "Downloading",
    osVersion: "5.2.1.3",
  },
  {
    serialNo: "JTD-714362",
    theatreName: "Lister",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    bandwidth: "1 Gbps",
    avgBandwidth: "812 Kbps",
    deviceStatus: "Online",
    downloadStatus: "Downloading",
    osVersion: "5.2.1.3",
  },
  {
    serialNo: "JTD-661243",
    theatreName: "Hello Cafe",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    bandwidth: "1 Gbps",
    avgBandwidth: "919 Kbps",
    deviceStatus: "Online",
    downloadStatus: "Downloading",
    osVersion: "5.2.1.3",
  },
  {
    serialNo: "JTD-623422",
    theatreName: "Jane Kirk",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    bandwidth: "1 Gbps",
    avgBandwidth: "812 Kbps",
    deviceStatus: "Online",
    downloadStatus: "Downloading",
    osVersion: "5.2.1.3",
  },
  {
    serialNo: "JTD-512123",
    theatreName: "Juhu",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    bandwidth: "1 Gbps",
    avgBandwidth: "919 Kbps",
    deviceStatus: "Online",
    downloadStatus: "Downloading",
    osVersion: "5.2.1.3",
  },
];
