const appliances = [
  {
    serialNo: "JTD-512312",
    theatreName: "Kriplle Square",
    location: {
      city: "New Delhi",
      state: "Delhi",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "812 Kbps",
    planStartDate: "2023-10-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Downloaded",
    osVersion: "5.2.1.3",
    storage: "828 GB",
  },
  {
    serialNo: "JTD-512313",
    theatreName: "Silver Screen",
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "500 Mbps",
    avgBandwidth: "450 Kbps",
    planStartDate: "2023-11-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "500 GB",
  },
  {
    serialNo: "JTD-512314",
    theatreName: "Majestic",
    location: {
      city: "Chennai",
      state: "Tamil Nadu",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "950 Kbps",
    planStartDate: "2023-09-15T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Unarchiving",
    osVersion: "5.2.1.3",
    storage: "1 TB",
  },
  {
    serialNo: "JTD-512315",
    theatreName: "PVR Cinemas",
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "2 Gbps",
    avgBandwidth: "1.5 Mbps",
    planStartDate: "2023-08-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "2 TB",
  },
  {
    serialNo: "JTD-512316",
    theatreName: "Inox",
    location: {
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "500 Mbps",
    avgBandwidth: "400 Kbps",
    planStartDate: "2023-07-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Scheduled",
    osVersion: "5.2.1.3",
    storage: "750 GB",
  },
  {
    serialNo: "JTD-512317",
    theatreName: "Cinepolis",
    location: {
      city: "Pune",
      state: "Maharashtra",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "700 Kbps",
    planStartDate: "2023-06-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "900 GB",
  },
  {
    serialNo: "JTD-512318",
    theatreName: "Big Cinemas",
    location: {
      city: "Kolkata",
      state: "West Bengal",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "750 Mbps",
    avgBandwidth: "600 Kbps",
    planStartDate: "2023-05-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Downloading",
    osVersion: "5.2.1.3",
    storage: "650 GB",
  },
  {
    serialNo: "JTD-512319",
    theatreName: "Carnival Cinemas",
    location: {
      city: "Ahmedabad",
      state: "Gujarat",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "850 Kbps",
    planStartDate: "2023-04-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "1 TB",
  },
  {
    serialNo: "JTD-512320",
    theatreName: "M2K",
    location: {
      city: "Gurgaon",
      state: "Haryana",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1.5 Gbps",
    avgBandwidth: "1 Mbps",
    planStartDate: "2023-03-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Completed",
    osVersion: "5.2.1.3",
    storage: "500 GB",
  },
  {
    serialNo: "JTD-512321",
    theatreName: "DT Cinemas",
    location: {
      city: "Noida",
      state: "Uttar Pradesh",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "2 Gbps",
    avgBandwidth: "1.2 Mbps",
    planStartDate: "2023-02-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "1.5 TB",
  },
  {
    serialNo: "JTD-512322",
    theatreName: "Wave Cinemas",
    location: {
      city: "Lucknow",
      state: "Uttar Pradesh",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "750 Mbps",
    avgBandwidth: "650 Kbps",
    planStartDate: "2023-01-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Archived",
    osVersion: "5.2.1.3",
    storage: "1 TB",
  },
  {
    serialNo: "JTD-512323",
    theatreName: "Sathyam Cinemas",
    location: {
      city: "Chennai",
      state: "Tamil Nadu",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "800 Kbps",
    planStartDate: "2022-12-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "700 GB",
  },
  {
    serialNo: "JTD-512324",
    theatreName: "Urvashi Cinemas",
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "500 Mbps",
    avgBandwidth: "450 Kbps",
    planStartDate: "2022-11-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Scheduled",
    osVersion: "5.2.1.3",
    storage: "600 GB",
  },
  {
    serialNo: "JTD-512325",
    theatreName: "Raj Mandir",
    location: {
      city: "Jaipur",
      state: "Rajasthan",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "900 Kbps",
    planStartDate: "2022-10-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "1.2 TB",
  },
  {
    serialNo: "JTD-512326",
    theatreName: "E-Square",
    location: {
      city: "Pune",
      state: "Maharashtra",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "500 Mbps",
    avgBandwidth: "420 Kbps",
    planStartDate: "2022-09-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Downloading",
    osVersion: "5.2.1.3",
    storage: "800 GB",
  },
  {
    serialNo: "JTD-512327",
    theatreName: "Orion Mall",
    location: {
      city: "Bengaluru",
      state: "Karnataka",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1.5 Gbps",
    avgBandwidth: "1.1 Mbps",
    planStartDate: "2022-08-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "2 TB",
  },
  {
    serialNo: "JTD-512328",
    theatreName: "Miraj Cinemas",
    location: {
      city: "Delhi",
      state: "Delhi",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "750 Mbps",
    avgBandwidth: "700 Kbps",
    planStartDate: "2022-07-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Completed",
    osVersion: "5.2.1.3",
    storage: "900 GB",
  },
  {
    serialNo: "JTD-512329",
    theatreName: "Prasads IMAX",
    location: {
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "820 Kbps",
    planStartDate: "2022-06-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "1 TB",
  },
  {
    serialNo: "JTD-512330",
    theatreName: "SRS Cinemas",
    location: {
      city: "Faridabad",
      state: "Haryana",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "500 Mbps",
    avgBandwidth: "450 Kbps",
    planStartDate: "2022-05-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Archived",
    osVersion: "5.2.1.3",
    storage: "500 GB",
  },
  {
    serialNo: "JTD-512331",
    theatreName: "Movietime",
    location: {
      city: "Noida",
      state: "Uttar Pradesh",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "800 Kbps",
    planStartDate: "2022-04-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "1 TB",
  },
  {
    serialNo: "JTD-512332",
    theatreName: "Carnival Cinemas",
    location: {
      city: "Chandigarh",
      state: "Punjab",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "850 Kbps",
    planStartDate: "2022-03-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Scheduled",
    osVersion: "5.2.1.3",
    storage: "1.5 TB",
  },
  {
    serialNo: "JTD-512333",
    theatreName: "Fun Cinemas",
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "500 Mbps",
    avgBandwidth: "400 Kbps",
    planStartDate: "2022-02-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "500 GB",
  },
  {
    serialNo: "JTD-512334",
    theatreName: "PVR Cinemas",
    location: {
      city: "Kolkata",
      state: "West Bengal",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1.5 Gbps",
    avgBandwidth: "1.2 Mbps",
    planStartDate: "2022-01-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Downloading",
    osVersion: "5.2.1.3",
    storage: "2 TB",
  },
  {
    serialNo: "JTD-512335",
    theatreName: "Inox",
    location: {
      city: "Surat",
      state: "Gujarat",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "750 Mbps",
    avgBandwidth: "650 Kbps",
    planStartDate: "2021-12-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "750 GB",
  },
  {
    serialNo: "JTD-512336",
    theatreName: "Cinepolis",
    location: {
      city: "Lucknow",
      state: "Uttar Pradesh",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "900 Kbps",
    planStartDate: "2021-11-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Completed",
    osVersion: "5.2.1.3",
    storage: "1 TB",
  },
  {
    serialNo: "JTD-512337",
    theatreName: "PVR",
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "750 Kbps",
    planStartDate: "2021-10-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "1.2 TB",
  },
  {
    serialNo: "JTD-512338",
    theatreName: "Inox",
    location: {
      city: "Nagpur",
      state: "Maharashtra",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "500 Mbps",
    avgBandwidth: "450 Kbps",
    planStartDate: "2021-09-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Archived",
    osVersion: "5.2.1.3",
    storage: "600 GB",
  },
  {
    serialNo: "JTD-512339",
    theatreName: "SRS Cinemas",
    location: {
      city: "Faridabad",
      state: "Haryana",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "800 Kbps",
    planStartDate: "2021-08-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Offline",
    downloadStatus: "Failed",
    osVersion: "5.2.1.3",
    storage: "900 GB",
  },
  {
    serialNo: "JTD-512340",
    theatreName: "Miraj Cinemas",
    location: {
      city: "Delhi",
      state: "Delhi",
      country: "India",
    },
    ispPaymentResponsibility: "Qube",
    bandwidth: "1 Gbps",
    avgBandwidth: "850 Kbps",
    planStartDate: "2021-07-01T10:00:00Z",
    billingCycle: "Monthly",
    deviceStatus: "Online",
    downloadStatus: "Scheduled",
    osVersion: "5.2.1.3",
    storage: "1 TB",
  },
];

module.exports = appliances;
